services:
  - type: web
    name: gcode-returner-api
    env: python
    region: oregon  # Choose region closest to your users
    plan: starter
    branch: main  # Adjust to your deployment branch
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p logs media db staticfiles
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      gunicorn gcode_returner.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --max-requests 1000 --max-requests-jitter 50 --preload --access-logfile - --error-logfile -
    envVars:
      - key: SECRET_KEY
        generateValue: true  # Render will generate a secure secret key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"  # This allows all Render subdomains
      - key: CORS_ALLOWED_ORIGINS
        value: "https://signature-eu.web.app"
      - key: TRUSTED_FRONTEND_ORIGINS
        value: "https://signature-eu.web.app"
      - key: FRONTEND_SIGNING_KEY
        value: "signature-app-for-my-project-2025"  # Use your actual signing key
      - key: COMMON_DIR
        value: "/opt/render/project/src"
      - key: MAX_UPLOAD_SIZE
        value: "10485760"
      - key: LOG_LEVEL
        value: "INFO"
      - key: API_RATE_LIMIT
        value: "100/hour"
      - key: PYTHON_VERSION
        value: "3.9.18"
    disk:
      name: sqlite-disk
      mountPath: /opt/render/project/src/db
      sizeGB: 1  # 1GB should be sufficient for SQLite database